version: '2.1'

services:
  dtests:
    build: .
    volumes:
      - .:/usr/src/cstar/cassandra-dtest
      - .m2:/home/cassandra/.m2

  unittests:
    build: .
    environment:
      - ONLY_UNIT_TESTS=true
    volumes:
      - .:/usr/src/cstar/cassandra-dtest
      - .m2:/home/cassandra/.m2
